name: convert .ipynb into .html

on:
  push:
    branches:
      - main

jobs:
  convert-notebooks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install converter
        run: |
          pip install nbconvert

      - name: convert .ipynb into .html
        run: |
          jupyter nbconvert --to html notebooks/*.ipynb

      - name: Save HTML files
        run: |
          git add .
          git commit -m "convert .ipynb into .html"
          git push
